# Generated by Django 3.1 on 2020-08-17 00:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_applications_candidates'),
    ]

    operations = [
        migrations.AddField(
            model_name='postings',
            name='posting_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 17, 0, 30, 14, 680312, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
